export const BREEDS = [
  "SRD",
  "Abissínio",
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "American Pit Bull Terrier",
  "American Shorthair",
  "American Staff. Terrier",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Bernese Mountain Dog",
  "Bichon Frisé",
  "Border Collie",
  "Borzoi",
  "Boston Terrier",
  "Boxer",
  "British",
  "Bull Terrier",
  "Bulldog Americano",
  "Bulldog Francês",
  "Bulldog Inglês",
  "Bulmastife",
  "Cão da Serra da Estrela",
  "Chihuahua",
  "Chinese Crested Dog",
  "Chow Chow",
  "Cocker Spaniel Americano",
  "Cocker Spaniel Inglês",
  "Collie",
  "Cornish Rex",
  "Dachshund",
  "Dálmata",
  "Dandie Dinmont Terrier",
  "Dobermann",
  "Dogo Argentino",
  "Dogue de Bordeaux",
  "Dogui Alemão",
  "Exótico",
  "Fila Brasileiro",
  "Fox Paulistinha",
  "Fox Terrier",
  "Golden Retriever",
  "Greyhound",
  "Himalaia",
  "Husky Siberiano",
  "Kerry Blue Terrier",
  "Kuvasz",
  "Labrador",
  "Lhasa Apso",
  "Lulu da Pomerânia",
  "Malamute do Alaska",
  "Maltês",
  "Mastiff",
  "Mastim Napolitano",
  "Old English Sheepdog",
  "Oriental",
  "Pastor Alemão",
  "Pastor Belga Groenandael",
  "Pastor Branco",
  "Pastor de Shetland",
  "Pêlo Curto Brasileiro",
  "Pequinês",
  "Persa",
  "Pinscher",
  "Pointer Alemão",
  "Pointer Inglês",
  "Poodle Anão",
  "Poodle Médio",
  "Poodle Standart",
  "Poodle Toy",
  "Pug",
  "Puli",
  "Retriever do Labrador",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Sagrado da Birmânia",
  "Samoieda",
  "São Bernardo",
  "Schipperke",
  "Schnauzer Gigante",
  "Schnauzer Miniatura",
  "Schnauzer Standard",
  "Scottish Terrier",
  "Setter Gordon",
  "Setter Inglês",
  "Setter Irlandês",
  "Shar-Pei",
  "Shiba",
  "Shih Tzu",
  "Siamês",
  "Spitz Alemão (Pomerânia)",
  "Springer Spaniel Inglês",
  "Terra Nova",
  "Terrier Brasileiro",
  "Weimaraner",
  "West Highland White Terrier",
  "Whippet",
  "Yorkshire Terrier",
  "Outro",
] as const
