CREATE TABLE IF NOT EXISTS medical_records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  medicalHistoryId INTEGER REFERENCES medical_histories (id),
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  symptomatology TEXT DEFAULT '',
  anamnesis TEXT DEFAULT '',
  diagnostics TEXT DEFAULT '',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
