CREATE TABLE IF NOT EXISTS medical_histories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  petId INTEGER REFERENCES pets (id),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
